# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: ko-KR
tone_instructions: "Be ASSERTIVE on Zero-Tolerance rules. Focus on AWS security best practices."
early_access: true

reviews:
  profile: assertive
  high_level_summary: true
  poem: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - "main"
      - "develop"
  path_filters:
    - "!**/.terraform/**"
    - "!**/*.tfstate"
    - "!**/*.tfstate.backup"
    - "!**/terraform.tfvars"
    - "!**/node_modules/**"
  path_instructions:
    - path: "terraform/modules/**/*.tf"
      instructions: |
        CRITICAL RULES:
        1. Required Tags: merge(local.required_tags, {...}) pattern required
        2. KMS Encryption: Customer-managed KMS keys required, no AES256
        3. Naming: Resources use kebab-case, variables use snake_case
        4. No Hardcoded Secrets
    - path: "terraform/environments/**/*.tf"
      instructions: |
        CRITICAL RULES:
        1. Required Tags Pattern: merge(local.required_tags, {...})
        2. KMS Encryption for all resources
        3. Environment consistency check
    - path: "**/*security*.tf"
      instructions: |
        SECURITY GROUP RULES:
        1. No 0.0.0.0/0 with all ports
        2. No dangerous ports (22, 3389, 3306, 5432) exposed to internet
        3. Description required for all security groups
    - path: "**/*s3*.tf"
      instructions: |
        S3 RULES:
        1. Public access block required
        2. KMS encryption required (no AES256)
        3. Versioning recommended
    - path: "**/*rds*.tf"
      instructions: |
        RDS RULES:
        1. No publicly_accessible = true
        2. storage_encrypted = true with KMS
        3. No hardcoded passwords
        4. Production: multi_az = true, backup_retention >= 7
  tools:
    gitleaks:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
