version: 0.1

projects:
  # Monitoring module cost estimation
  - path: terraform/monitoring
    name: monitoring
    terraform_workspace: default

  # Atlantis module cost estimation
  - path: terraform/atlantis
    name: atlantis
    terraform_workspace: default

# Cost policy thresholds
cost_policy:
  # Warning at +10% increase
  warning_threshold_percent: 10

  # Block at +30% increase
  blocking_threshold_percent: 30

  # Show breakdown for resources above this amount
  breakdown_threshold: 1.0

  # Currency settings
  currency: USD

# Output settings
output:
  # Include resource-level breakdown
  show_skipped: true

  # Group by service
  group_by: service

  # Fields to display
  fields:
    - monthlyQuantity
    - unit
    - monthlyCost
    - hourlyCost

# GitHub integration
github:
  # Behavior for PR comments
  behavior: update

  # Show cost changes in table format
  show_changed_resources: true
  show_unchanged_resources: false

  # Tag for cost comment identification
  tag: infracost
