name: Documentation Validation

on:
  pull_request:
    paths:
      - 'terraform/**/README.md'
      - 'docs/**/*.md'
      - '.github/workflows/docs-validation.yml'
      - 'scripts/check-terraform-docs.sh'
  push:
    branches:
      - main
    paths:
      - 'terraform/**/README.md'
      - 'docs/**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-docs:
    name: Validate Terraform Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check documentation script exists
        run: |
          if [[ ! -f "./scripts/check-terraform-docs.sh" ]]; then
            echo "❌ ERROR: scripts/check-terraform-docs.sh not found"
            exit 1
          fi
          chmod +x ./scripts/check-terraform-docs.sh

      - name: Validate all Terraform package documentation
        id: validate
        run: |
          echo "📚 Starting documentation validation..."
          ./scripts/check-terraform-docs.sh > /tmp/docs-validation.log 2>&1
          VALIDATION_EXIT_CODE=$?

          echo "exit_code=$VALIDATION_EXIT_CODE" >> $GITHUB_OUTPUT

          # Store validation output for PR comment
          cat /tmp/docs-validation.log

          exit $VALIDATION_EXIT_CODE

      - name: Comment PR with validation results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const validationLog = fs.readFileSync('/tmp/docs-validation.log', 'utf8');
            const exitCode = '${{ steps.validate.outputs.exit_code }}';

            let emoji = '✅';
            let title = '문서 검증 성공';
            let color = 'green';

            if (exitCode !== '0') {
              emoji = '❌';
              title = '문서 검증 실패';
              color = 'red';
            }

            const body = `## ${emoji} ${title}

            <details>
            <summary>📋 검증 결과 상세보기</summary>

            \`\`\`
            ${validationLog}
            \`\`\`

            </details>

            ---

            ### 📖 문서화 가이드라인

            **필수 섹션:**
            - 개요
            - 사용 방법
            - Variables
            - Outputs

            **권장 섹션:**
            - 보안 고려사항 (Security Considerations)
            - Troubleshooting
            - 예제 (Examples)

            **추가 요구사항:**
            - Last Updated 날짜 포함
            - 코드 예제 최소 3개
            - examples/basic 디렉토리 및 README.md

            📘 자세한 내용은 [Module Standards Guide](../../docs/modules/MODULE_STANDARDS_GUIDE.md)를 참고하세요.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Upload validation log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-validation-log
          path: /tmp/docs-validation.log
          retention-days: 7

  check-links:
    name: Check Documentation Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check links in documentation
        run: |
          echo "🔗 Checking links in markdown files..."

          # Find all markdown files
          find . -name "*.md" \
            -not -path "./node_modules/*" \
            -not -path "./.terraform/*" \
            -not -path "./.git/*" \
            -print0 | \
            xargs -0 -n1 markdown-link-check -c .github/markdown-link-check-config.json || true
        continue-on-error: true

      - name: Comment PR with broken links
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## ⚠️ 문서 링크 검증 경고

            일부 문서에서 깨진 링크가 발견되었습니다.

            GitHub Actions 로그를 확인하여 문제가 되는 링크를 수정해주세요.

            💡 **참고:** 내부 링크는 로컬 환경에서 확인하시고, 외부 링크는 정기적으로 검토해주세요.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  summary:
    name: Documentation Validation Summary
    runs-on: ubuntu-latest
    needs: [validate-docs, check-links]
    if: always()

    steps:
      - name: Summary
        run: |
          echo "## 📚 문서 검증 완료" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 검증 결과:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Terraform 문서 검증: ${{ needs.validate-docs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- 🔗 링크 검증: ${{ needs.check-links.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.validate-docs.result }}" != "success" ]]; then
            echo "⚠️ 문서 검증에 실패했습니다. 위 로그를 확인하여 문제를 해결해주세요." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
